#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2019 Gerasimov Alexander <samik.mechanic@gmail.com>
#

# action icons
ICON_CHECK  = "✅"
ICON_RAGE   = "🔥"
ICON_FAST   = "🚽"
ICON_ARS    = "📦"
ICON_THINK  = "💤"
ICON_CANCEL = "❌"
ICON_LATE   = "⏰"
ICON_START  = "▶️"
ICON_STOP   = "⏹"
ICON_EXIT   = "#️⃣"
ICON_FR  = "🗓 Пт"
ICON_SAT = "🗓 Сб"
ICON_SUN = "🗓 Вс"

# callbacks
CHECK_CALLBACK_PREFIX = "Check_"
CHECK_CHECK_CALLBACK  = CHECK_CALLBACK_PREFIX+ICON_CHECK
CHECK_RAGE_CALLBACK   = CHECK_CALLBACK_PREFIX+ICON_RAGE
CHECK_FAST_CALLBACK   = CHECK_CALLBACK_PREFIX+ICON_FAST
CHECK_ARS_CALLBACK    = CHECK_CALLBACK_PREFIX+ICON_ARS
CHECK_THINK_CALLBACK  = CHECK_CALLBACK_PREFIX+ICON_THINK
CHECK_CANCEL_CALLBACK = CHECK_CALLBACK_PREFIX+ICON_CANCEL
CHECK_LATE_CALLBACK   = CHECK_CALLBACK_PREFIX+ICON_LATE
CHECK_START_CALLBACK  = CHECK_CALLBACK_PREFIX+ICON_START
CHECK_STOP_CALLBACK   = CHECK_CALLBACK_PREFIX+ICON_STOP
CHECK_EXIT_CALLBACK   = CHECK_CALLBACK_PREFIX+ICON_EXIT

PRECHECK_CALLBACK_PREFIX = "PreCheck_"
PRECHECK_FR_CALLBACK     = PRECHECK_CALLBACK_PREFIX+ICON_FR
PRECHECK_SAT_CALLBACK    = PRECHECK_CALLBACK_PREFIX+ICON_SAT
PRECHECK_SUN_CALLBACK    = PRECHECK_CALLBACK_PREFIX+ICON_SUN
PRECHECK_FULL_CALLBACK   = PRECHECK_CALLBACK_PREFIX+ICON_CHECK
PRECHECK_THINK_CALLBACK  = PRECHECK_CALLBACK_PREFIX+ICON_THINK
PRECHECK_CANCEL_CALLBACK = PRECHECK_CALLBACK_PREFIX+ICON_CANCEL
PRECHECK_STOP_CALLBACK   = PRECHECK_CALLBACK_PREFIX+ICON_STOP

ARS_CALLBACK_PREFIX = "Ars_"
ARS_0_CALLBACK    = ARS_CALLBACK_PREFIX+"0"
ARS_8_CALLBACK    = ARS_CALLBACK_PREFIX+"8"
ARS_9_CALLBACK    = ARS_CALLBACK_PREFIX+"9"
ARS_10_CALLBACK   = ARS_CALLBACK_PREFIX+"10"
ARS_11_CALLBACK   = ARS_CALLBACK_PREFIX+"11"
ARS_12_CALLBACK   = ARS_CALLBACK_PREFIX+"12"
ARS_13_CALLBACK   = ARS_CALLBACK_PREFIX+"13"
ARS_14_CALLBACK   = ARS_CALLBACK_PREFIX+"14"
ARS_24_CALLBACK   = ARS_CALLBACK_PREFIX+"24"
ARS_27_CALLBACK   = ARS_CALLBACK_PREFIX+"27"
ARS_30_CALLBACK   = ARS_CALLBACK_PREFIX+"30"
ARS_33_CALLBACK   = ARS_CALLBACK_PREFIX+"33"
ARS_36_CALLBACK   = ARS_CALLBACK_PREFIX+"36"
ARS_39_CALLBACK   = ARS_CALLBACK_PREFIX+"39"
ARS_42_CALLBACK   = ARS_CALLBACK_PREFIX+"42"
ARS_FULL_CALLBACK = ARS_CALLBACK_PREFIX+"Full"
